trigger:
- master

pr:
- '*'

jobs:
- job: Build
  displayName: Build and Push Docker Image
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      packageType: 'sdk'
      version: '6.x' # Use the appropriate .NET 6 version

  - script: |
      # Install Docker
      sudo apt-get update
      sudo apt-get install -y docker.io

      # Log in to Docker registry (Azure Container Registry)
      docker login imagensapigabriel.azurecr.io -u <username> -p <password>

      # Build the Docker image
      docker build -t usuarioapi:latest -f .**/Dockerfile .

      # Push the Docker image to the registry
      docker push imagensapigabriel.azurecr.io/usuarioapi:latest
    displayName: 'Build and Push Docker Image'

- job: RunIntegrationTests
  displayName: Run Integration Tests
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      # Clone your repository or checkout your source code here if necessary
      
      # Restore dependencies and build the project
      dotnet restore
      dotnet build

      # Execute integration tests (replace with your test command)
      dotnet test .**/UsuarioAPI.Login.testes.csproj
    displayName: 'Run Integration Tests'

  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/TestResults/*.trx'
    condition: always()